[package]
name = "surrealdb-bb8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bb8 = "0.8.1"
async-trait = "0.1"
surrealdb = { version = "1.0.0", features = ["http", "kv-mem", "kv-tikv"] }
